module.exports = [
  {
    name:'Captain America The First Avenger',
    numberInCollection:219,
    popType: 'Emerald City Comic Con exclusive',
    img:'https://cf1.s3.souqcdn.com/item/2018/06/13/35/87/27/63/item_XL_35872763_139507376.jpg',
    value:50,
    collection_:'Marvel',
    qty:1,
  },
  {
    name:'Wolverine',
    numberInCollection:05,
    popType: 'common',
    img:'https://images-na.ssl-images-amazon.com/images/I/61EicsqfXTL._SX425_.jpg',
    value:20,
    collection_:'Marvel',
    qty:2,
  },
  {
    name:'Loki',
    numberInCollection:16,
    popType: 'San Diego Comic Con Exclusive',
    img:'https://images-na.ssl-images-amazon.com/images/I/51n1EgM%2BtvL._SX425_.jpg',
    value:800,
    collection_:'Marvel',
    qty:1,
  },
  {
    name:'Dr. Doom',
    numberInCollection:17,
    popType: 'Common Valted',
    img:'https://images-na.ssl-images-amazon.com/images/I/71kYF1EPZFL._SX425_.jpg',
    value:150,
    collection_:'Marvel',
    qty:1,
  },
  {
    name:'Boo Monsters Inc',
    numberInCollection:20,
    popType: 'Common Valted',
    img:'https://images-na.ssl-images-amazon.com/images/I/51QxD1c40aL._SX425_.jpg',
    value:250,
    collection_:'Disney',
    qty:1,
  },
  {
    name:'Peter Parker',
    numberInCollection:34,
    popType: 'Comikaze Comic Con Exclusive',
    img:'https://cdn.poppriceguide.com/guide/itmimg/588_PeterParker_1520615330.jpg',
    value:200,
    collection_:'Marvel',
    qty:1,
  },
  {
    name:'Tony Stark',
    numberInCollection:32,
    popType: 'San Diego Comic Con',
    img:'https://images-na.ssl-images-amazon.com/images/I/511mcJaTTPL._SX425_.jpg',
    value:300,
    collection_:'Marvel',
    qty:1,
  },
  {
    name:'Iron Patriot',
    numberInCollection:25,
    popType: 'Common Valted',
    img:'https://images-na.ssl-images-amazon.com/images/I/71tm1Yi5RIL._SX425_.jpg',
    value:80,
    collection_:'Marvel',
    qty:1,
  },
  {
    name:'Thanos',
    numberInCollection:308,
    popType: '10 INCH POP Target Exclsusive',
    img:'https://cache.popcultcha.com.au/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/v/avengers-3-infinity-war-thanos-10-inch-pop-vinyl-figure.1534315617.png',
    value:75,
    collection_:'Marvel',
    qty:2,
  },
  {
    name:'Thor With Stormbreaker',
    numberInCollection:286,
    popType: 'Asia Exclusive',
    img:'https://media.karousell.com/media/photos/products/2018/11/21/110840_199674653_thumbnail0_progressive_thumbnail',
    value:160,
    collection_:'Marvel',
    qty:1,
  }
]
